### ISSUE TITLE
Parameters site didn‘t show new parameters to setup

### ISSUE THREAD

**Issue by ambergerit** [MaximilianClemens/checkmk_fritzbox#2]
Hello Maximilian,

I have the same issue. I installed it using the mkp command. After that you wrote „there should now be a new option "Query SmartHome Devices"“ but it is not. Only the old one, where i can set the timeout value. 

In Host and service parameters there is a new entry „Settings for Fritz!Box Smarthome Devices“ where i could set parameters for the smarthome warning/critical states. 

The (bevore plugin installation) activated fritz Hosts get now error state:

Fetching 'agent'...
Failed: [special_fritzbox] Agent exited with code 2: usage: agent_fritzbox [-h] [--debug] [--timeout TIMEOUT] [--check-upnp]
                      [--check-smarthome]
                      host [username] [password] [port] [{http,https}]
agent_fritzbox: error: port must be between 1 and 65565
(!!)

Finished. Click on the icon to download the data.

So it will use the new plugin, but i cannot configure it, to get it working, due the parameters are not show up in wato.
But if i cannot set the values in the host and service parameters how will,i get this working again. Seems that the new parameters site isn‘t been loading in „Check state of Fritz!Box Devices“ so the system loads the original check_mk site (i‘ve attatched a screenshot).
Can you provide a solution for this? 
![B6E78C71-CD0A-44A9-9C63-841625354087](https://user-images.githubusercontent.com/6476053/95666718-ba929f00-0b5c-11eb-90f1-5574fa5e4238.jpeg)

_Originally posted by @ambergerit in https://github.com/MaximilianClemens/checkmk_fritzbox/issues/1#issuecomment-706622675_

**Comment by MaximilianClemens** [comment]
Hi @ambergerit,

sorry that it is not working.
I will try to fix this today at the evening.

**Comment by MaximilianClemens** [comment]
Hi again @ambergerit,

I think the problem was that I only developed and tested with checkmk 1.4.0.
Now I updated all files to work with **1.6.0**. And there is no need to overlay the original checkmk fritzbox agent, as it seems to support multiplate datasource agents.

How ever, may can you try to install the new mkp [(v.03)](https://github.com/MaximilianClemens/checkmk_fritzbox/releases/tag/v0.3). (**Please uninstall the v0.2 before (mkp remove fritzbox_smarthome)**).

Here some screens which may help:
![grafik](https://user-images.githubusercontent.com/5416563/95676900-fdd32900-0bc1-11eb-860d-12458bc90b53.png)
![grafik](https://user-images.githubusercontent.com/5416563/95676894-e85dff00-0bc1-11eb-9041-a30f290f1e57.png)
![grafik](https://user-images.githubusercontent.com/5416563/95676912-1f341500-0bc2-11eb-95ba-f3ec2890cac2.png)
![grafik](https://user-images.githubusercontent.com/5416563/95676922-38d55c80-0bc2-11eb-9236-1abc86671e79.png)


Regards Max

**Comment by ambergerit** [comment]
Hi @MaximilianClemens,

Yes that‘s it. works fine! could you possible add the posibility to connect to Fritz!Box devices with password only (as it is normally in the internal network) without username? So maybe to choose it at the properties, whitch connection mode should be used?

**Comment by MaximilianClemens** [comment]
Hi @ambergerit,

can you try [v0.4.1](https://github.com/MaximilianClemens/checkmk_fritzbox/releases/tag/v0.4.1) and give me feedback, if it works for you?

The options for the Agent are now optional:
![grafik](https://user-images.githubusercontent.com/5416563/95689755-3bac6d80-0c13-11eb-8ac6-d7043822dfe8.png)

Update the mkp should work now
`su - myomdsite`
`cd ~/var/check_mk/packages`
`wget https://github.com/MaximilianClemens/checkmk_fritzbox/releases/download/v0.4.1/fritzbox_smarthome-0.4.1.mkp`
`mkp install fritzbox_smarthome-0.4.1.mkp`

But you have to reenter the Credentials at the Host and Service Parameters as I changed the variable names

Regards Max

**Comment by ambergerit** [comment]
Hi @MaximilianClemens,

This Version works very good, thank you very mutch for the changes you made!

**Comment by MaximilianClemens** [comment]
Thanks for feedback :)
I will close this issue
